name: tests

on:
  push:
  workflow_dispatch:

jobs:
  actions:
    name: Run Linters and Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install --progress-bar off -r requirements.txt -r requirements-dev.txt
    - name: Run linters
      run: make lint
    - name: Download model
      run: make download
    - name: Run tests
      run: make test
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: tests/.artifacts/*.html
        retention-days: 90
